### ISSUE TITLE
Trouble with Docker container

### ISSUE THREAD

**Issue by altano** [zerotier/ZeroTierOne#1579]
.env:
```
ZEROTIER_NETWORK_ID=...
```

docker-compose.yaml:
```
version: "3.7"

volumes:
  db:

services:
  zerotier:
    image: zerotier/zerotier:1.8.4
    command: "${ZEROTIER_NETWORK_ID}"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - db:/var/lib/zerotier-one
```

# First run
```
> docker-compose up
Removing network zerotier-container-stack_default
Removing volume zerotier-container-stack_db
Removing volume zerotier-container-stack_zerotier-custom-db
Creating network "zerotier-container-stack_default" with the default driver
Creating volume "zerotier-container-stack_db" with default driver
Creating volume "zerotier-container-stack_zerotier-custom-db" with default driver
Pulling zerotier (zerotier/zerotier:1.8.4)...
1.8.4: Pulling from zerotier/zerotier
Digest: sha256:b57e76e4291fbc26e1c75df07bc3534e9180457343c7ceff5d7ac8c4e25f6f44
Status: Downloaded newer image for zerotier/zerotier:1.8.4
Creating zerotier-container-stack_zerotier_1 ... done
Attaching to zerotier-container-stack_zerotier_1
zerotier_1  | starting zerotier
zerotier_1  | cat: /var/lib/zerotier-one/zerotier-one.pid: No such file or directory
zerotier_1  | cat: /var/lib/zerotier-one/zerotier-one.pid: No such file or directory
zerotier_1  | joining networks: 1c33c1ced0d58dd6
zerotier_1  | joining 1c33c1ced0d58dd6
zerotier_1  | 0 join connection failed
zerotier_1  | joining 1c33c1ced0d58dd6 failed; trying again in 1s
```

# Authorization

Authorize node in ZeroTier Central
