### ISSUE TITLE
Slow speed using ZeroTier

### ISSUE THREAD

**Issue by ilya-yarets** [zerotier/ZeroTierOne#2375]
Hey guys!

I’m having an issue with ZeroTier. My server, configured with the settings below, is experiencing very slow speeds when I’m uploading or downloading files. The server is located in Belarus, and I’m connecting from a client. When I use Cloudflare for similar tasks, I can reach speeds of up to 20 Mbps for both upload and download, but with ZeroTier, it’s significantly slower.

Here's what’s going on:

- **Expected behavior:** I expected to achieve similar speeds (around 20 Mbps) as I do with Cloudflare.
- **What’s happening:** ZeroTier’s speed is much slower than expected, making file transfers almost unusable.
- **Steps to reproduce:** I connect to the server via ZeroTier from the client and attempt to upload or download files. Every time, the speed is very slow.
- **Relevant console output:** No specific errors in the console; the connection seems stable but very slow.
- **Operating system and ZeroTier version:** 
   - Client OS: MacOS 14.3
   - Server OS: Running via Docker on Synology NAS (Docker image: zerotier/zerotier-synology:latest)
   - ZeroTier version: 1.14.0
   - ZeroTier client version: 1.12.2

Here is the server setup (Docker Compose):
```yaml
version: "3.8"
services:
  zerotier:
    container_name: zerotier
    image: zerotier/zerotier-synology:latest
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: "host"
    restart: unless-stopped
```

Any ideas on what could be causing this issue or how I can fix it? I’m happy to provide any more details if needed. Any help would be greatly appreciated!

Thanks in advance!
