### ISSUE TITLE
[Feature Request] Add label for source_node_id in zerotier promethues metrics

### ISSUE THREAD

**Issue by umarhussain15** [zerotier/ZeroTierOne#2402]
Hi, 
Currently, the Prometheus metrics exported by Zerotier don't include the source zerotier node which generated them. The documentation says to manually add this label in the scraping job config. This will become a lot of manual works if we want to monitor a lot of zerotier nodes. Also in case of running the zerotier nodes in Kubernetes as pods we will not be able to put this information on ServiceMonitor or PodMonitor due to dynamic nature of the pods.

I suggest enriching the metrics emitted by Zerotier to also include the source node id in the labels of the metrics which are specific to that node. As the node already has the information about its own id it can be a simple operation. For example, the updated metrics will then look like this:
```
zt_peer_path_count{source_id="wxy123456z",node_id="abc12345de",status="alive"} 0
```

Thank you.

**Comment by YiannisH** [comment]
As a workaround you could add a label source_node_id. I agree that it would help if its added by the zerotier service without needing to add it in prometheus conf manually.

```yaml
  - job_name: zerotier
    honor_labels: true
    scrape_interval: 60s
    metrics_path: /metrics
    static_configs:
    - targets:
      - 192.192.252.1:9993
      labels:
        group: zerotier-one
        source_node_id: fakenodeid
    authorization:
      credentials: dummycreds
```
