### ISSUE TITLE
[Feature Request] client hostname propagation to name field

### ISSUE THREAD

**Issue by wainaxman** [zerotier/ZeroTierOne#475]
Highly valuable work guys. If deployed to multiple systems at the same time, it would be very helpful, while joining a network to propagate the hostname to the name field. This way it would be easy to distinguish the automatically deployed clients after joining. I have seen this feature in Hamachi. Actually it is the only feature holding us back from rolling this out at our company.

My current workaround is to ssh to the client, then entering the hostname into the name field manually in the webinterface. Or could it be that i've missed something?

**Comment by dch** [comment]
You probably want to do this via API directly. I initialise new hosts
via ansible, and the ansible controller has the privilege token to write
the name into the connection. You could do this via curl or puppet or
whatever, the key thing is that you can't trust the local client with
the API key. I dropped the full ansible role here for others to borrow,
the bits you're interested in are first joining, then POSTing with the
token to get authorised. In my case, this authorisation is running on
the ansible controller, not on the client.

```yaml
---
- name: zerotier | install pkg
  pkgng:
    name: "{{ item }}"
    state: present
  with_items:
    - net/zerotier
  notify: zerotier | restart
  tags:
    - zerotier

- name: zerotier | add ansible fact collector
  copy:
    content: |
      #!/bin/sh
      /usr/local/bin/zerotier-cli -j info
    dest: /usr/local/etc/ansible/facts.d/zerotier.fact
    mode: 0750
    owner: root
    group: wheel
  tags:
    - zerotier

- name: zerotier | enable daemon
  copy:
    content: |
      zerotier_enable="YES"
    dest: /etc/rc.conf.d/zerotier
    mode: 0440
  notify: zerotier | restart
  tags:
    - zerotier

- name: zerotier | start daemon
  service:
    name: zerotier
    state: started
  tags:
    - zerotier

- name: zerotier | get local node address
  # check_mode: no means "always run this task"
  command: /usr/local/bin/zerotier-cli -j info
  register: zerotier_info
  check_mode: no
  changed_when: false
  tags:
    - zerotier

- name: zerotier | dump info response
  debug:
    var:  zerotier_info.stdout
    verbosity: 2
  when: not ansible_check_mode
  tags:
    - debug
    - zerotier

- name: zerotier | join network
  command: /usr/local/bin/zerotier-cli -j join {{ net.zerotier.network
  }}
  register: zerotier_network
  when: not ansible_check_mode
  changed_when: false
  tags:
    - zerotier

- name: zerotier | dump network response
  debug:
    var:  zerotier_network.stdout
    verbosity: 2
  when: not ansible_check_mode
  tags:
    - debug
    - zerotier

- name: zerotier | register responses
  set_fact:
    zerotier_address: "{{ (zerotier_info.stdout |from_json).address }}"
    zerotier_device:  "{{ (zerotier_network.stdout
    |from_json).portDeviceName }}"
    zerotier_name:    "{{ (zerotier_network.stdout |from_json).name }}"
    zerotier_ip:      "{{ (zerotier_network.stdout
    |from_json).assignedAddresses }}"
    zerotier_status:  "{{ (zerotier_network.stdout |from_json).status
    }}"
  when: not ansible_check_mode
  tags:
    - zerotier

- name: zerotier | authorise this connection
  uri:
    url: https://my.zerotier.com/api/network/{{ net.zerotier.network
    }}/member/{{ zerotier_address }}
    method: POST
    HEADER_Authorization: "Bearer {{ net.zerotier.token }}"
    body_format: json
    body:
      name: "{{ inventory_hostname }}"
      config:
        authorized: true
    return_content: yes
  register: zerotier_authorisation
  when: not ansible_check_mode and (zerotier_status != "OK" or
  zerotier_name != "{{ inventory_hostname }}")
  tags:
    - zerotier

- name: zerotier | dump authorisation response
  debug:
    var:  zerotier_authorisation
    verbosity: 2
  when: not ansible_check_mode
  tags:
    - debug
    - zerotier

- name: zerotier | dump inventory configuration
  debug:
    var: ansible_local.zerotier
    verbosity: 2
  tags:
    - debug
    - zerotier
```
