### ISSUE TITLE
Issue with Centos and FirewallD

### ISSUE THREAD

**Issue by zaharidichev** [zerotier/ZeroTierOne#698]
Hi there, 

I have been using Zerotier for a few days now and am experiencing strange connection problems when I setup my firewall. I am using CentOS with FirewallD and as suggested by the documentation I have whitelisted UDP traffic on 9993. So really my configuration is as follows: 

```
trusted (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: zt0
  sources:
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

drop (active)
  target: DROP
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: ntp
  ports: 9993/udp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

Network interface associations: 

drop
  interfaces: eth0
trusted
  interfaces: zt0
```

According to the documentation on FirewallD, I have configured the drop zone to drop all traffic except for 9993/udp. That being said I am experiencing sporadic ssh connection drops when connected to the node. Could this be due to the fact that for some reason ZT is still using the slow relaying? Is there anything additional that I should be configuring ? My suspicions are further confirmed by the fact that when I disable the firewall completely, I stop experiencing connection problems.

Netstat UDP output looks like: 

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 0.0.0.0:54283           0.0.0.0:*                           760/dhclient
udp        0      0 0.0.0.0:68              0.0.0.0:*                           760/dhclient
udp        0      0 195.201.103.103:42462   0.0.0.0:*                           9718/zerotier-one
udp        0      0 195.201.103.103:42463   0.0.0.0:*                           9718/zerotier-one
udp        0      0 195.201.103.103:9993    0.0.0.0:*                           9718/zerotier-one
udp6       0      0 :::62891                :::*                                760/dhclient
udp6       0      0 2a01:4f8:1c0c:7cb:42462 :::*                                9718/zerotier-one
udp6       0      0 2a01:4f8:1c0c:7cb:42463 :::*                                9718/zerotier-one
udp6       0      0 2a01:4f8:1c0c:7cb1:9993 :::*                                9718/zerotier-one
```

I wonder what are ports such as 42462 and 42463 used for and should there be any additional firewall config for them as well ?
